/** PriomGL Apex 4.0 — native organic sculpting. */
(function(global){'use strict';const P=global.PriomGL;if(!P)return;const {Primitives,Geometry}=P;
function hash(x,y,z,s=0){const n=Math.sin(x*127.1+y*311.7+z*74.7+s*19.19)*43758.5453123;return n-Math.floor(n)}
function noise3(x,y,z){const X=Math.floor(x),Y=Math.floor(y),Z=Math.floor(z),fx=x-X,fy=y-Y,fz=z-Z,s=t=>t*t*(3-2*t),u=s(fx),v=s(fy),w=s(fz),c=(a,b,d)=>hash(X+a,Y+b,Z+d);const x0=c(0,0,0)*(1-u)+c(1,0,0)*u,x1=c(0,1,0)*(1-u)+c(1,1,0)*u,x2=c(0,0,1)*(1-u)+c(1,0,1)*u,x3=c(0,1,1)*(1-u)+c(1,1,1)*u;return (x0*(1-v)+x1*v)*(1-w)+(x2*(1-v)+x3*v)*w}
function fbm(x,y,z,oct=4){let a=.5,f=1,v=0,n=0;for(let i=0;i<oct;i++){v+=noise3(x*f,y*f,z*f)*a;n+=a;a*=.5;f*=2}return v/n}
function organicSphere(radius=1,sx=1,sy=1,sz=1,segments=40,rings=24,seed=1,amp=.035){const g=Primitives.sphere(radius,segments,rings),p=g.attributes.position.data;for(let i=0;i<p.length;i+=3){const x=p[i]/radius,y=p[i+1]/radius,z=p[i+2]/radius,n=(fbm(x*3.2+seed,y*3.2,z*3.2,4)-.5)*2,d=Math.sin((z+.2)*7+seed*.31)*Math.sin((x-.1)*5.7-seed*.17)*.35,k=1+n*amp+d*amp*.35;p[i]=x*radius*sx*k;p[i+1]=y*radius*sy*(1+n*amp*.72);p[i+2]=z*radius*sz*k}g.computeNormals();return g}
function loftRings(rings,radial=16){const pos=[],uv=[],idx=[];for(let j=0;j<rings.length;j++){const r=rings[j],t=j/(rings.length-1),tw=r.twist||0;for(let i=0;i<=radial;i++){const a=i/radial*Math.PI*2+tw,x=Math.cos(a),z=Math.sin(a);pos.push(r.center[0]+x*r.rx,r.center[1],r.center[2]+z*r.rz);uv.push(i/radial,t)}}for(let j=0;j<rings.length-1;j++)for(let i=0;i<radial;i++){const a=j*(radial+1)+i,b=a+radial+1;idx.push(a,b,a+1,b,b+1,a+1)}const g=new Geometry();g.setAttribute('position',pos,3).setAttribute('uv',uv,2).setIndex(idx);g.computeNormals();return g}
function capsule(a,b,r0,r1,radial=14,segments=5){const rings=[];for(let j=0;j<=segments;j++){const t=j/segments;rings.push({center:[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t],rx:r0+(r1-r0)*t,rz:r0+(r1-r0)*t})}return loftRings(rings,radial)}
function subdivide(g,it=1){let cur=g;for(let k=0;k<it;k++){const pos=cur.attributes.position.data,idx=cur.indices,uv=cur.attributes.uv?.data,P2=Array.from(pos),U2=uv?Array.from(uv):[],I2=[],cache=new Map(),mid=(a,b)=>{const key=a<b?a+'_'+b:b+'_'+a;if(cache.has(key))return cache.get(key);const ia=a*3,ib=b*3,n=P2.length/3;P2.push((pos[ia]+pos[ib])*.5,(pos[ia+1]+pos[ib+1])*.5,(pos[ia+2]+pos[ib+2])*.5);if(uv){const ua=a*2,ub=b*2;U2.push((uv[ua]+uv[ub])*.5,(uv[ua+1]+uv[ub+1])*.5)}cache.set(key,n);return n};for(let t=0;t<idx.length;t+=3){const a=idx[t],b=idx[t+1],c=idx[t+2],ab=mid(a,b),bc=mid(b,c),ca=mid(c,a);I2.push(a,ab,ca,ab,b,bc,ca,bc,c,ab,bc,ca)}const ng=new Geometry();ng.setAttribute('position',P2,3).setAttribute('uv',U2.length?U2:new Float32Array(P2.length/3*2),2).setIndex(I2);ng.computeNormals();cur=ng}return cur}
P.Sculpting={noise3,fbm,organicSphere,loftRings,capsule,subdivide};})(typeof window!=='undefined'?window:globalThis);
