(function(global){'use strict';const P=global.PriomGL=global.PriomGL||{};const M=global.PriomMath;
const {Geometry,Primitives,Mesh,Material,InstancedMesh}=P;
function rng(seed){let s=seed|0;return()=>{s=(Math.imul(1664525,s)+1013904223)|0;return(s>>>0)/4294967296}}
function bladeGeo(){const g=new Geometry();g.setAttribute('position',[-.035,0,0,.035,0,0,.0,.42,.0,-.035,0,.0,.035,0,.0,.0,.36,.045],3);g.setAttribute('normal',[0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0],3);g.setAttribute('uv',[0,0,1,0,.5,1,0,0,1,0,.5,1],2);g.setIndex([0,1,2,3,5,4]);return g}
function leafGeo(){const g=new Geometry();g.setAttribute('position',[-.12,0,0,.12,0,0,0,.34,0,0,0,.045],3);g.setAttribute('normal',[0,0,1,0,0,1,0,0,1,0,0,1],3);g.setAttribute('uv',[0,0,1,0,.5,1,.5,.15],2);g.setIndex([0,1,2,0,2,3]);return g}
function riverGeo(terrain,seed){const R=rng(seed),pts=[];for(let i=0;i<18;i++){const z=-90+i*10.5;const x=Math.sin(i*.73)*12+Math.sin(i*1.7)*4;const y=terrain.getHeight(x,z)+.12;pts.push([x,y,z])}const pos=[],n=[],uv=[],idx=[];for(let i=0;i<pts.length;i++){const p=pts[i],prev=pts[Math.max(0,i-1)],next=pts[Math.min(pts.length-1,i+1)];let tx=next[0]-prev[0],tz=next[2]-prev[2],l=Math.hypot(tx,tz)||1;tx/=l;tz/=l;const nx=-tz,nz=tx,w=2.8+R()*.8;pos.push(p[0]+nx*w,p[1],p[2]+nz*w,p[0]-nx*w,p[1],p[2]-nz*w);n.push(0,1,0,0,1,0);uv.push(i/3,0,i/3,1);if(i<pts.length-1){const a=i*2,b=a+2;idx.push(a,a+1,b,b,b+1,a+1)}}const g=new Geometry();g.setAttribute('position',pos,3).setAttribute('normal',n,3).setAttribute('uv',uv,2).setIndex(idx);return g}
class ApexWorldSystem{
 constructor(engine){this.engine=engine;this.seed=(engine.terrainGen?.seed||1337)^0x5A17;this.inst=[];this.animalCount=0;this.ready=false;}
 _mat(name,color,rough,nature=0,shader='pbr'){return new Material({albedo:new M.Color(...color),roughness:rough,metallic:0,ao:.9,natureType:nature,shader,textureFamily:name})}
 build(){const e=this.engine,t=e.terrainGen;if(!t)return false;this._buildRiver(t);this._buildGrass(t);this._buildLeaves(t);this._improveSun();this.ready=true;return true}
 _buildRiver(t){const g=riverGeo(t,this.seed);const m=this._mat('water',[.025,.18,.24],.08,0,'water');const water=new Mesh(g,m);water.name='Apex5_River_Main';water.castShadow=false;water.receiveShadow=true;this.engine.scene.add(water);this.engine.scene.waterLevel=t.getWaterLevel?t.getWaterLevel():0;this.river=water;}
 _scatter(t,count,geo,mat,name,scaleFn){const im=new InstancedMesh(geo,mat,count);im.name=name;const R=rng(this.seed+count);let n=0;for(let i=0;i<count;i++){const x=(R()-.5)*180,z=(R()-.5)*180,y=t.getHeight(x,z);if(y<1.0||y>24)continue;const s=scaleFn(R(),x,z);im.setInstance(n++,x,y+.01,z,R()*Math.PI*2,s[0],s[1],s[2],.72+.22*R(),.78+.22*R(),.52+.25*R(),R()*6.28)}im.count=n;this.engine.scene.add(im);this.inst.push(im);return im}
 _buildGrass(t){const m=this._mat('grass',[.10,.32,.055],.88,2);this._scatter(t,1800,bladeGeo(),m,'Apex5_Grass',randomValue=>[.7+randomValue*.6,.55+randomValue*1.2,.7+randomValue*.6]);}
 _buildLeaves(t){const m=this._mat('leaf',[.055,.28,.045],.78,2);this._scatter(t,650,leafGeo(),m,'Apex5_LeafLayer',randomValue=>[.55+randomValue*.8,.55+randomValue*1.1,.55+randomValue*.8]);}
 _improveSun(){const e=this.engine;if(!e._apex5SunPatched){const old=e._updateSun.bind(e);e._updateSun=(t)=>{old(t);const s=e.scene.sun;const day=(t*.012+.8)%(Math.PI*2);const elev=Math.sin(day);const az=day; // world-space sun; never camera-relative
s.direction.set(Math.cos(az)*.72,-Math.max(.05,elev*.92+.04),Math.sin(az)*.72).normalize();const warm=Math.max(0,1-Math.max(0,elev)*1.7);s.color.set(1.0,.96-warm*.25,.88-warm*.34);s.intensity=.95+Math.max(0,elev)*1.55};e._apex5SunPatched=true}}
 spawnFauna(count=9){const e=this.engine,w=e.worldAI,t=e.terrainGen;if(!w||!t)return 0;const supported=[['ciervo',.45,6,false],['lobo',.4,8,false],['oso',.65,4,false]];for(let i=0;i<count;i++){const sp=supported[i%supported.length],R=rng((this.seed+i*919)^0x991);let x=0,z=0,y=0;for(let k=0;k<30;k++){x=(R()-.5)*130;z=(R()-.5)*130;y=t.getHeight(x,z);if(y>2&&y<22)break}const animal=w._createAnimal({name:sp[0],speed:sp[2],radius:sp[1],prey:sp[0]!=='lobo',flying:false,social:sp[0]!=='oso',diet:sp[0]==='lobo'?'carnivore':'herbivore'},x,y,z,w._nextAnimalId++);w.animals.push(animal);this.animalCount++}return this.animalCount}
}
P.ApexWorldSystem=ApexWorldSystem;
})(typeof window!=='undefined'?window:globalThis);
